### ISSUE TITLE
CDXML Parsing Problem

### ISSUE THREAD

**Issue by blakeo2** [SEDenmarkLab/molli#132]
I found an interesting problem with a phosphine structure being drawn in certain ways. Essentially with the hash going towards the phosphine, it doesn't give the correct stereochemistry, but when the hash goes away, it fixes the problem.

[hash_problem.zip](https://github.com/SEDenmarkLab/molli/files/15410229/hash_problem.zip)

**Comment by esalx** [comment]
I inspected this a little bit, and I think it's a curious case. In both cases parsing is correct! The only difference is that in one case the whole planar phosphine fragment is bent out of the way, and in the other case phosphine stays in plane, whereas the whole substituent is displaced out of plane. Key is directionality of the bond, 

I will close this now because the behavior is consistent with the expectations from the parser, though it may become  a discussion about parsing.
